language: go
go:
  - 1.x
  - tip
install:
  - go get github.com/nsf/gocode
  - go get ./...
  - go get -t ./...
script:
  - gofmt -l -w *.go */*.go | perl -pe 'END { exit !!$. }'
  - go test ./...
  - rm -f tmp_gore_session*.go
  - rm -f gore_extarnal_*
